/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Producto;

/**
 *
 * @author Susana
 */
public class ActualizarCliente extends javax.swing.JFrame {
    int rut_cliente = 0;
   

    /**
     * Creates new form ActualizarCliente
     */
    public ActualizarCliente() {
        initComponents();
          this.getContentPane().setBackground(new Color ( 201, 228, 197));
          
                        Image  icon = new ImageIcon(getClass().getResource("/img/iconohojas.png")).getImage();
              setIconImage(icon);
              
               this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelBuscarNombreCliente = new javax.swing.JLabel();
        TextFieldNombreCliente = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        LabelNombreCliente = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelDireccionEnvio = new javax.swing.JLabel();
        TextFieldDireccionEnvio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaProductosComprados = new javax.swing.JTextArea();
        ButtonActualizar = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        LabelComuna = new javax.swing.JLabel();
        TextFieldComuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualiza los datos del cliente");

        LabelBuscarNombreCliente.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelBuscarNombreCliente.setText("Nombre del cliente:");

        ButtonBuscar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonBuscar.setText("BUSCAR");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        LabelNombreCliente.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelNombreCliente.setText("Nombre:");

        LabelDireccionEnvio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelDireccionEnvio.setText("Dirección de envío:");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel1.setText("Productos comprados: ");

        TextAreaProductosComprados.setColumns(20);
        TextAreaProductosComprados.setRows(5);
        jScrollPane1.setViewportView(TextAreaProductosComprados);

        ButtonActualizar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonActualizar.setText("ACTUALIZAR");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonLimpiar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonLimpiar.setText("LIMPIAR");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonSalir.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonSalir.setText("CANCELAR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        LabelComuna.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelComuna.setText("Comuna:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonActualizar)
                    .addComponent(LabelDireccionEnvio)
                    .addComponent(LabelBuscarNombreCliente)
                    .addComponent(LabelComuna)
                    .addComponent(jLabel1)
                    .addComponent(LabelNombreCliente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextFieldComuna, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldDireccionEnvio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSalir)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBuscarNombreCliente)
                    .addComponent(TextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDireccionEnvio)
                    .addComponent(TextFieldDireccionEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonLimpiar)
                    .addComponent(ButtonSalir))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
       Principal prin = new Principal();
       prin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
   String nombreCliente = TextFieldNombreCliente.getText();
        Controlador con = new Controlador();
        Cliente cliente = con.buscarPorNombreCliente(nombreCliente);
        if(cliente.getRut_cliente() != 0){            
            TextFieldNombre.setText(cliente.getNombre_cliente());
            TextFieldDireccionEnvio.setText(cliente.getDireccion_envio());
            TextFieldComuna.setText(cliente.getComuna());
            TextAreaProductosComprados.setText(cliente.getProductos_comprados());
            rut_cliente = cliente.getRut_cliente();      
        }else{
            JOptionPane.showMessageDialog(null, "Cliente  no encontrado");
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
           TextAreaProductosComprados.setText(" ");
           TextFieldDireccionEnvio.setText(" ");
          TextFieldNombre.setText(" ");
          TextFieldComuna.setText(" ");
       
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        String nombre_cliente, direccion_envio, comuna, productos_comprados;           


        nombre_cliente = TextFieldNombre.getText();
        if (nombre_cliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre y apellido del cliente", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldNombre.requestFocus();
            return;
        }

        direccion_envio = TextFieldDireccionEnvio.getText();
        if ( direccion_envio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese dirección de envío", "Validación", JOptionPane.WARNING_MESSAGE);
           TextFieldDireccionEnvio.requestFocus();
            return;
        }
        
         comuna= TextFieldComuna.getText();
        if ( comuna.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese dirección de envío", "Validación", JOptionPane.WARNING_MESSAGE);
           TextFieldComuna.requestFocus();
            return;
        }
        
          productos_comprados = TextAreaProductosComprados.getText();
        if ( productos_comprados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese dirección de envío", "Validación", JOptionPane.WARNING_MESSAGE);
           TextAreaProductosComprados.requestFocus();
            return;
        }


        Cliente cliente = new Cliente(rut_cliente, nombre_cliente, direccion_envio, comuna, productos_comprados);

        Controlador con = new Controlador();

        
        if (con.actualizarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Se Actualizo cliente  " + cliente.getNombre_cliente(), "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se actualizó cliente  " + cliente.getNombre_cliente(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_ButtonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel LabelBuscarNombreCliente;
    private javax.swing.JLabel LabelComuna;
    private javax.swing.JLabel LabelDireccionEnvio;
    private javax.swing.JLabel LabelNombreCliente;
    private javax.swing.JTextArea TextAreaProductosComprados;
    private javax.swing.JTextField TextFieldComuna;
    private javax.swing.JTextField TextFieldDireccionEnvio;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNombreCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
