/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Image;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Susana
 */
public class ActualizarProducto extends javax.swing.JFrame {
       private int id_producto = 0;
    

    /**
     * Creates new form ActualizarProducto
     */
    public ActualizarProducto() {
        initComponents();
          this.getContentPane().setBackground(new Color ( 201, 228, 197));
          
               Image  icon = new ImageIcon(getClass().getResource("/img/iconohojas.png")).getImage();
              setIconImage(icon);
              
               this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombreProducto = new javax.swing.JLabel();
        TextFieldNombreProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextFieldTipoProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextFieldMaterial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldColor = new javax.swing.JTextField();
        LabelPrecio = new javax.swing.JLabel();
        TextFieldPrecio = new javax.swing.JTextField();
        LabelStock = new javax.swing.JLabel();
        TextFieldStock = new javax.swing.JTextField();
        ButtonActualizar = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        LabelBuscarNombre = new javax.swing.JLabel();
        TextFieldBuscarNombre = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualiza información del producto");

        LabelNombreProducto.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelNombreProducto.setText("Nombre: ");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel1.setText("Tipo:");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel2.setText("Material:");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel3.setText("Color:");

        TextFieldColor.setToolTipText("");

        LabelPrecio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelPrecio.setText("Precio:");

        LabelStock.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelStock.setText("Stock:");

        ButtonActualizar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonActualizar.setText("ACTUALIZAR");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonLimpiar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonLimpiar.setText("LIMPIAR");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonCancelar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonCancelar.setText("CANCELAR");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        LabelBuscarNombre.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelBuscarNombre.setText("Nombre del producto: ");

        ButtonBuscar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonBuscar.setText("BUSCAR");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonActualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(LabelNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(LabelPrecio)
                        .addComponent(LabelStock))
                    .addComponent(LabelBuscarNombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextFieldBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(ButtonLimpiar)
                        .addGap(57, 57, 57)
                        .addComponent(ButtonCancelar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBuscarNombre)
                    .addComponent(TextFieldBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreProducto)
                    .addComponent(TextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(LabelStock))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonLimpiar)
                    .addComponent(ButtonCancelar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {
     
             String nombre_producto, tipo_producto, material, color;          
        int precio;
       int stock;

        nombre_producto = TextFieldNombreProducto.getText();
        if (nombre_producto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese título", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldNombreProducto.requestFocus();
            return;
        }

       tipo_producto = TextFieldTipoProducto.getText();
        if (tipo_producto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese autor", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldTipoProducto.requestFocus();
            return;
        }
        
          material = TextFieldMaterial.getText();
        if (material.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese autor", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldMaterial.requestFocus();
            return;
        }
        
           color = TextFieldColor.getText();
        if (color.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese autor", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldColor.requestFocus();
            return;
        }
     

        try {
            precio = Integer.parseInt(TextFieldPrecio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Elprecio debe ser un número", "Validación", JOptionPane.WARNING_MESSAGE);
          TextFieldPrecio.requestFocus();
            return;
        }
        
                try {
            stock = Integer.parseInt(TextFieldStock.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Elprecio debe ser un número", "Validación", JOptionPane.WARNING_MESSAGE);
          TextFieldStock.requestFocus();
            return;
        }

       Producto producto = new Producto(id_producto, nombre_producto, tipo_producto, material, color, precio, stock);

        Controlador con= new Controlador();

        
        if (con.actualizar(producto)) {
            JOptionPane.showMessageDialog(this, "Se Actualizo producto  " + producto.getNombre_producto(), "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se actualizó producto  " + producto.getNombre_producto(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }                                                

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        
        TextFieldNombreProducto.setText(" ");
        TextFieldTipoProducto.setText(" ");
        TextFieldMaterial.setText(" ");
        TextFieldColor.setText(" ");
        TextFieldPrecio.setText(" ");
        TextFieldStock.setText(" ");
        

        
        
        
        
        
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
           String nombreProducto = TextFieldBuscarNombre.getText();
         Controlador con = new Controlador ();
        Producto producto  =  con.buscarPorNombre(nombreProducto);
        if(producto.getId_producto() != 0){
             TextFieldNombreProducto.setText(producto.getNombre_producto());
             TextFieldTipoProducto.setText(producto.getTipo_producto());
             TextFieldMaterial.setText(producto.getMaterial());
             TextFieldColor.setText(producto.getColor());
             TextFieldPrecio.setText(String.valueOf(producto.getPrecio()));
              TextFieldStock.setText(String.valueOf(producto.getStock()));
              id_producto  = producto.getId_producto();
               
 
        }else{
            JOptionPane.showMessageDialog(null, "Producto no encontrado");
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JLabel LabelBuscarNombre;
    private javax.swing.JLabel LabelNombreProducto;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JLabel LabelStock;
    private javax.swing.JTextField TextFieldBuscarNombre;
    private javax.swing.JTextField TextFieldColor;
    private javax.swing.JTextField TextFieldMaterial;
    private javax.swing.JTextField TextFieldNombreProducto;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JTextField TextFieldStock;
    private javax.swing.JTextField TextFieldTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
