/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Usuario;

/**
 *
 * @author Susana
 */
public class AgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
          this.getContentPane().setBackground(new Color ( 201, 228, 197));
          
           Image  icon = new ImageIcon(getClass().getResource("/img/iconohojas.png")).getImage();
              setIconImage(icon);
              
               this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LabelIDProducto = new javax.swing.JLabel();
        LabeltipoProducto = new javax.swing.JLabel();
        LabelMaterial = new javax.swing.JLabel();
        LabelColor = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        LabelStock = new javax.swing.JLabel();
        TextFieldTipoProducto = new javax.swing.JTextField();
        TextFieldNombreProducto = new javax.swing.JTextField();
        TextFieldMaterial = new javax.swing.JTextField();
        TextFieldColor = new javax.swing.JTextField();
        TextFieldPrecio = new javax.swing.JTextField();
        TextFieldStock = new javax.swing.JTextField();
        ButtonAgregarProducto = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR PRODUCTO");

        LabelIDProducto.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelIDProducto.setText("Nombre:");

        LabeltipoProducto.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabeltipoProducto.setText("Tipo de producto:");

        LabelMaterial.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelMaterial.setText("Material:");

        LabelColor.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelColor.setText("Color:");

        LabelPrecio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelPrecio.setText("Precio:");

        LabelStock.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelStock.setText("Stock:");

        TextFieldTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTipoProductoActionPerformed(evt);
            }
        });

        ButtonAgregarProducto.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonAgregarProducto.setText("AGREGAR");
        ButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarProductoActionPerformed(evt);
            }
        });

        ButtonLimpiar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonLimpiar.setText("LIMPIAR");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonSalir.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonSalir.setText("SALIR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIDProducto)
                            .addComponent(LabeltipoProducto)
                            .addComponent(LabelMaterial)
                            .addComponent(LabelColor)
                            .addComponent(LabelPrecio)
                            .addComponent(LabelStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldNombreProducto)
                            .addComponent(TextFieldTipoProducto)
                            .addComponent(TextFieldMaterial)
                            .addComponent(TextFieldColor)
                            .addComponent(TextFieldPrecio)
                            .addComponent(TextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDProducto)
                    .addComponent(TextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabeltipoProducto)
                    .addComponent(TextFieldTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaterial)
                    .addComponent(TextFieldMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelColor)
                    .addComponent(TextFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAgregarProducto)
                    .addComponent(ButtonLimpiar)
                    .addComponent(ButtonSalir))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTipoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTipoProductoActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarProductoActionPerformed
       
        String nombre_producto, tipo_producto, material, color;       
           int precio;
           int stock;         
      
        nombre_producto =TextFieldNombreProducto.getText();
        if (nombre_producto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldNombreProducto.requestFocus();
            return;
        }

       tipo_producto = TextFieldTipoProducto.getText();
        if ( tipo_producto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese tipo de producto", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldTipoProducto.requestFocus();
            return;
        }
        
        material  = TextFieldMaterial.getText();
        if ( material.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese tipo de producto", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldMaterial.requestFocus();
            return;
        }
        
              color  = TextFieldColor.getText();
        if ( color.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese tipo de producto", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldColor.requestFocus();
            return;
        }

        try {
            precio = Integer.parseInt(TextFieldPrecio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número", "Validación", JOptionPane.WARNING_MESSAGE);
          TextFieldPrecio.requestFocus();
            return;
        }
        
              try {
           stock = Integer.parseInt(TextFieldStock.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El stock debe ser un número", "Validación", JOptionPane.WARNING_MESSAGE);
          TextFieldStock.requestFocus();
            return;
        }        

        Producto producto1 = new Producto (0, nombre_producto, tipo_producto, material, color, precio, stock);

        Controlador con= new Controlador ();

        if (con.buscarPorId(producto1.getId_producto()).getNombre_producto() == null) {
            if (con.agregarProducto(producto1)) {
                JOptionPane.showMessageDialog(this, "Se agregó producto " + producto1.getNombre_producto(), "Información", JOptionPane.INFORMATION_MESSAGE);
           
            TextFieldNombreProducto.setText(" ");
            TextFieldTipoProducto.setText(" ");
            TextFieldMaterial.setText(" ");
            TextFieldColor.setText(" ");
            TextFieldPrecio.setText(" ");
            TextFieldStock.setText(" ");
            } else {
                JOptionPane.showMessageDialog(this, "No se agregó producto " + producto1.getNombre_producto(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Producto " + producto1.getNombre_producto()+ " ya existe", "Información", JOptionPane.WARNING_MESSAGE);
        }
        
       
        
        
    }//GEN-LAST:event_ButtonAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarProducto;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel LabelColor;
    private javax.swing.JLabel LabelIDProducto;
    private javax.swing.JLabel LabelMaterial;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JLabel LabelStock;
    private javax.swing.JLabel LabeltipoProducto;
    private javax.swing.JTextField TextFieldColor;
    private javax.swing.JTextField TextFieldMaterial;
    private javax.swing.JTextField TextFieldNombreProducto;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JTextField TextFieldStock;
    private javax.swing.JTextField TextFieldTipoProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
