/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Producto;

/**
 *
 * @author Susana
 */
public class AgregarCliente extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCliente
     */
    public AgregarCliente() {
        initComponents();
          this.getContentPane().setBackground(new Color ( 201, 228, 197));
          
           Image  icon = new ImageIcon(getClass().getResource("/img/iconohojas.png")).getImage();
              setIconImage(icon);
              
               this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRutCliente = new javax.swing.JLabel();
        LabelNombreCliente = new javax.swing.JLabel();
        LabelDireccionEnvio = new javax.swing.JLabel();
        LabelProductosComprados = new javax.swing.JLabel();
        TextFieldRutCliente = new javax.swing.JTextField();
        TextFieldNombreCliente = new javax.swing.JTextField();
        TextFieldDireccionEnvio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaProductosComprados = new javax.swing.JTextArea();
        ButtonAgregarCliente = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        LabelComuna = new javax.swing.JLabel();
        TextFieldComuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agrega un cliente nuevo");

        LabelRutCliente.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelRutCliente.setText("Ingrese el rut del cliente (sin puntos ni guion):");

        LabelNombreCliente.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelNombreCliente.setText("Nombre y apellido:");

        LabelDireccionEnvio.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelDireccionEnvio.setText("Dirección de envío:");

        LabelProductosComprados.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelProductosComprados.setText("Productos comprados (separados por coma):");

        TextFieldRutCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRutClienteActionPerformed(evt);
            }
        });

        TextAreaProductosComprados.setColumns(20);
        TextAreaProductosComprados.setRows(5);
        jScrollPane1.setViewportView(TextAreaProductosComprados);

        ButtonAgregarCliente.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonAgregarCliente.setText("AGREGAR");
        ButtonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarClienteActionPerformed(evt);
            }
        });

        ButtonSalir.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonSalir.setText("CANCELAR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        ButtonLimpiar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonLimpiar.setText("LIMPIAR");

        LabelComuna.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        LabelComuna.setText("Comuna:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelComuna)
                            .addComponent(LabelDireccionEnvio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNombreCliente)
                                    .addComponent(LabelRutCliente))
                                .addGap(2, 2, 2))
                            .addComponent(LabelProductosComprados, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextFieldRutCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldDireccionEnvio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldComuna, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonSalir)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreCliente)
                    .addComponent(TextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldDireccionEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDireccionEnvio))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelComuna))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProductosComprados)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAgregarCliente)
                            .addComponent(ButtonLimpiar)
                            .addComponent(ButtonSalir))
                        .addGap(40, 40, 40))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarClienteActionPerformed
      int rut_cliente;
      String nombre_cliente, direccion_envio, comuna, productos_comprados;
      
             try {
            rut_cliente= Integer.parseInt(TextFieldRutCliente.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El formato de rut no es válido", "Validación", JOptionPane.WARNING_MESSAGE);
         TextFieldRutCliente.requestFocus();
            return;
        }
           
        nombre_cliente =TextFieldNombreCliente.getText();
        if (nombre_cliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre y apellido del cliente", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldNombreCliente.requestFocus();
            return;
        }

       direccion_envio = TextFieldDireccionEnvio.getText();
        if ( direccion_envio .isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una dirección válida", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldDireccionEnvio.requestFocus();
            return;
        }
        
        comuna = TextFieldComuna.getText();
        if ( direccion_envio .isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una dirección válida", "Validación", JOptionPane.WARNING_MESSAGE);
            TextFieldComuna.requestFocus();
            return;
        }
        
        productos_comprados = TextAreaProductosComprados.getText();
        if ( productos_comprados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese al menos un producto", "Validación", JOptionPane.WARNING_MESSAGE);
           TextAreaProductosComprados.requestFocus();
            return;
        }
        
        Cliente cliente1 = new Cliente (rut_cliente, nombre_cliente, direccion_envio, comuna, productos_comprados);

        Controlador con= new Controlador ();

        if (con.buscarPorRut(cliente1.getRut_cliente()).getNombre_cliente() == null) {
            if (con.agregarCliente(cliente1)) {
                JOptionPane.showMessageDialog(this, "Se agregó cliente " + cliente1.getNombre_cliente(), "Información", JOptionPane.INFORMATION_MESSAGE);
           
            TextFieldRutCliente.setText(" ");
            TextFieldNombreCliente.setText(" ");
           TextFieldDireccionEnvio.setText(" ");
            TextAreaProductosComprados.setText(" ");
      
            } else {
                JOptionPane.showMessageDialog(this, "No se agregó cliente " + cliente1.getNombre_cliente(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cliente  " + cliente1.getNombre_cliente()+ " ya existe", "Información", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_ButtonAgregarClienteActionPerformed

    private void TextFieldRutClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRutClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRutClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarCliente;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel LabelComuna;
    private javax.swing.JLabel LabelDireccionEnvio;
    private javax.swing.JLabel LabelNombreCliente;
    private javax.swing.JLabel LabelProductosComprados;
    private javax.swing.JLabel LabelRutCliente;
    private javax.swing.JTextArea TextAreaProductosComprados;
    private javax.swing.JTextField TextFieldComuna;
    private javax.swing.JTextField TextFieldDireccionEnvio;
    private javax.swing.JTextField TextFieldNombreCliente;
    private javax.swing.JTextField TextFieldRutCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
